### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by PierreRambaud** [GotCms/GotCms#100]
Script helper not working, and add getServiceLocator method to return Service manager.

**Comment by kienle83** [comment]
Hi Pierre,

can you say why script does not work? i try to create a new script and a view with same name but they do not work like your sample "contact". do you have any idea? thanks you

**Comment by PierreRambaud** [comment]
Hi,
Can you tell me more about your script? Do you check php errors? How to you call its?
Regards

**Comment by kienle83** [comment]
I created a:
+ view with indentifier: search (with a form) 
<form action="<?php echo $this->escapeHtml($this->document(''search'')->getUrl()); ?>" method="post">

+ script with identifier "search": 
<?php echo 'Bonjour';

+ document with identifier "search". 

In frontend I call "/search" and see the form but if i click on submit button of form then i see nothing, although i have already script "search" . In script I want only to write something out like <?php echo 'Bonjour'; but it does not work.

In code, under the templates folder, I see file "search.phtml" (under script) and "search.phtml" (under view). I think the name of both files must be equals, but they are already the same :-(

**Comment by PierreRambaud** [comment]
It's not really working like that, you must call this->script('my-script-name');` like it's say in this page: http://got-cms.com/reference-guide/scripts

**Comment by kienle83** [comment]
ok that works now. merci beaucoup. I have one question more: how can I use parameter in url, for example "/search/:id", i have read #208, and i tried a litte and found that with GET works: $this->redirect()->toUrl('/search?id=bonjour'); but there is only with GET? do we have another methode?

**Comment by PierreRambaud** [comment]
Yes, it's only works with get parameters, / in url are split to check for document.

**Comment by kienle83** [comment]
thank you so much :-)
