### ISSUE TITLE
Add frontend user authentication module

### ISSUE THREAD

**Issue by PierreRambaud** [GotCms/GotCms#22]
Allow users to connect to frontend and backend simultaneously.

use Zend\Authentication\AuthenticationService,
    Zend\Authentication\Adapter,
    Zend\Authentication\Storage;

//backend
$backend_auth_adapter = new Adapter\DbTable($this->getAdapter());
$backend_auth_adapter->setTableName('admin_user');
$backend_auth_adapter->setIdentityColumn('login');
$backend_auth_adapter->setCredentialColumn('password');
$backend_auth_adapter->setIdentity($login);
$backend_auth_adapter->setCredential($password);

$backend_auth = new AuthenticationService(new Storage\Session('Zend_Auth_Backend'));
$result = $backend_auth->authenticate($backend_auth_adapter);
var_dump($result);

//Frontend
$frontend_auth_adapter = new Adapter\DbTable($this->getAdapter());
$frontend_auth_adapter->setTableName('user');
$frontend_auth_adapter->setIdentityColumn('login');
$frontend_auth_adapter->setCredentialColumn('password');
$frontend_auth_adapter->setIdentity($login);
$frontend_auth_adapter->setCredential($password);

$frontend_auth = new AuthenticationService(new Storage\Session('Zend_Auth_Frontend'));
$result = $frontend_auth->authenticate($frontend_auth_adapter);
var_dump($result);

**Comment by Sorny-net** [comment]
How can i make login form at frontend main page for users?

**Comment by PierreRambaud** [comment]
Hi,
By creating a custom modules that override layout, viewmodel to add user variables and for the form, create the form in view called by partial helper, and this view call a custom script that request a database. That depends on what you need exactly.
Regards,

**Comment by Sorny-net** [comment]
Thanks a lot! Have a good day!
