### ISSUE TITLE
Problem with Login - AuthenticationService

### ISSUE THREAD

**Issue by kienle83** [GotCms/GotCms#277]
Bonjour Pierre,

I had a problem with login. By method authenticate in Model of User (https://github.com/GotCms/GotCms/blob/master/library/Gc/User/Model.php):
```
if ($result->isValid()) {
$data = $authAdapter->getResultRowObject(null, 'password');
$this->setData((array) $data);
$this->setOrigData();
$auth->getStorage()->write($this);
$this->events()->trigger(CLASS, 'after.auth', $this);
return true;
}

```
$result is valid, method returns "true". But in Controller: $auth = $this->getServiceLocator()->get('Auth') returns false.

I think that error happen at line 90 of user model ($auth->getStorage()->write($this);), at this position model can be not saved into $auth.

Or error happen at line 72 of module.cofig.php (https://github.com/GotCms/GotCms/blob/master/module/GcFrontend/config/module.config.php):
return new AuthenticationService(new Storage\Session(UserModel::BACKEND_AUTH_NAMESPACE));

What do you think about this problem? Maybe because of session too?
P/S: i have read #127 , #265 :-) but i can not find the solution now. Could you suggest something for me?

**Comment by PierreRambaud** [comment]
Hi,
If you import your website, in core_config_data table, you must check the cookie_domain value and be sur the domain match with your virtualhost.
Be sure your php configuration is ok and you have the ability to write in your session directory.

Regards

**Comment by kienle83** [comment]
the cookie_domain is the reason :-) so many thanks :+1:
