### ISSUE TITLE
Website not working after install

### ISSUE THREAD

**Issue by SitoD** [GotCms/GotCms#279]
Hello,

Thank you for this nice project. I just have a problem, I installed correctly, and edited the /install page, but then it keeps directing me back to the install... where I see all the configuration is gone. I do the install again, and still the same....

So, no acces to website, or admin area....I don't know where to go from here, do you have an idea what can be wrong?

Regards!

**Comment by PierreRambaud** [comment]
Hi,

Did you see all processes running in `/install/complete` webpage? More, can you show me all php logs when this page is running? 
Logically if the installation processes passed, a file is created in `config/autoload/local.php` and it's impossible to go again on `/install`

Regards
