### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by e-v-medvedev** [GotCms/GotCms#283]
More documentation is needed. How and where i can create custom modules? Have you some decision for customer registration/authorization?

**Comment by PierreRambaud** [comment]
Hi,

I know, that's why I need some other developers and writers to improve documentation and code of this CMS.
Curently, if you need some example you can have a look in this directory : https://github.com/GotCms/GotCms/tree/master/library/Modules
I don't have any decision, everyone can contribute and add what they want :)

Regards

**Comment by e-v-medvedev** [comment]
I installed CMS and your modules. Everything works fine. But for creating custom modules i need to know how i can do it :-). That is why i need any documentation. Any at all. :-). Your CMS is the first, written on ZF2, which installed perfectly and works. And whow i can use Social?

**Comment by PierreRambaud** [comment]
Writing module is likely writing ZF2 modules, but they are for the backend but you can add a menu.phtml in your views to display it on the left side (https://github.com/GotCms/GotCms/blob/master/library/Modules/Social/views/social/menu.phtml).
If you want to use Social module, you can call the AddThisWidget Plugin like this:
```
    <?php echo $this->modulePlugin('Social', 'add-this-widget'); ?>
```

**Comment by e-v-medvedev** [comment]
And where i must to put my modules? I found out, that modules can be autoloaded from /extensions/zfModule. And what about namespaces? I created module Customer in this folder. Module.php works fine (i checked). module.config.php also loaded. I created IndexController in src/Customer/Controller with indexAction. 
This is content of module.config.php

return array(
    'controllers' => array(
        'invokables' => array(
            'CustomerController' => 'Customer\Controller\IndexController',
        ),
    ),
    'view_manager' => array(
        'template_path_stack' => array(
            'customer' => __DIR__ . '/../views',
        ),
    ),
    
    'router' => array(
        'routes' => array(
            'customer' => array(
                'type'    => 'Literal',
                'options' => array(
                    'route' => '/customer',
                    'defaults' => array(
                        'module'     =>'Customer',
                        'controller' => 'CustomerController',
                        'action'     => 'index',
                    ),
                ),
                'may_terminate' => true,
            ),
        ),
    ),
);

And here /customer i see error "An error occurred An error occurred during execution; please try again later." in admin(!) layout. What am i doing wrong?

**Comment by PierreRambaud** [comment]
If you want to add a Backend module, you must add it in Modules directory, ZfModules is exclusively for Zend Framework community modules.
By the way, to add the Backend Module, you must Install it directly in the CMS -> Modules -> Install, it will add a line in "module" table in the database.
If you must see more about what's happened, you can activate the debug mode in CMS -> Configuration.

**Comment by e-v-medvedev** [comment]
I now about "module" table :-). I need to create frontend login. And also i need role manager for frontend users. Can you give some advise?

**Comment by PierreRambaud** [comment]
You must create a custom module overriding frontend layout or using a view helper, and use a script to request your user database / table. That depends on what you need exactly.

**Comment by e-v-medvedev** [comment]
I thought that i needed a controller, as usually :-). I created login form, view and script. And now i think i have to do a backend module for managing customers? Or i can use default users and roles for frontend?

**Comment by PierreRambaud** [comment]
Custom modules controllers are only used for `/admin/modules`, if you want to use defaut table, be care with permissions, create a front-end_user table is safier. If you want to contribute you're welcome :)

**Comment by e-v-medvedev** [comment]
Yes, i want. I`ll try. :-) Thanks. May be i can write some manual, but only in russian. My english not well enough. :-) May be you add some interface for adding help pages? And tell me how i can add or remove translations. For example i want exclude fr_FR.

**Comment by PierreRambaud** [comment]
The documentation is currently only in english: https://github.com/GotCms/documentation/blob/master/reference-guide/modules.md 
If you want to contribute for translations: https://github.com/GotCms/GotCms/tree/master/data/install/translation
If you want to remove fr_FR translations, remove line in core_translate, I think something must be added during installation to only copy selected language.

**Comment by e-v-medvedev** [comment]
I fixed some errors in data/install/translation/ru_RU.php and filled empty fields. How i can send you result? And i downloaded documentation-master.zip. Will it be enough, if i cat translate files in it?

**Comment by PierreRambaud** [comment]
Working with github pull request is a better to contribute: https://help.github.com/articles/using-pull-requests/
For documentation, I create three directories, so you will be able to contribute in english and russian, even if you're not fluent (it will be better, I'll be able to edit english and translate in french ):)

**Comment by e-v-medvedev** [comment]
I tried to change ru_RU/discover/demo.md :-).

**Comment by e-v-medvedev** [comment]
I translated all that i could. For example https://github.com/e-v-medvedev/documentation/commit/c1aed5e0a5e12558d74a5b3f7acb1d1e928e4f51. But may be i did something wrong?

**Comment by e-v-medvedev** [comment]
This is my discover/demo.md https://github.com/e-v-medvedev/documentation/commit/35414a88169bd91299db0e43a1973606dbac7d04

**Comment by PierreRambaud** [comment]
Nothing, but I just closed this issue because it should be on this repository: https://github.com/GotCms/documentation ;)

**Comment by pinefirst** [comment]
I am interested in GotCms.
So i studied about it and practice it.
But I think it 's needed some more document.
For example, i 'm going to add captcha function in login, but there is no data.
and there is also no tutorial.

**Comment by Sorny-net** [comment]
> I am interested in GotCms.
> So i studied about it and practice it.
> But I think it 's needed some more document.
> For example, i 'm going to add captcha function in login, but there is no data.
> and there is also no tutorial.

Drop this shit into trash. Zend is die.
Try to use Laravel dude.

**Comment by PierreRambaud** [comment]
Agree with @Sorny-net Zend Framework is totally dead and shouldn't be used anymore.
