### ISSUE TITLE
Fixing admin translation problem

### ISSUE THREAD

**Issue by e-v-medvedev** [GotCms/GotCms#285]
I added this code
$out = array();
if (($handle = fopen(__DIR__ . DIRECTORY_SEPARATOR . "ru_RU.csv", "r")) !== FALSE) {
    while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
			$out[$data[0]] = $data[1];
    }
    fclose($handle);
}

return $out;

in data/translation and CSV file with lines like this
"-- Select --","-- Выбор --"
which was created by saving translations in ZIP.

Now my admin panel looks nice :-)

**Comment by PierreRambaud** [comment]
Hi,

I don't really understand where did you add this line? And what did you do exactly to have an error and what errror was displayed?

Regards

**Comment by e-v-medvedev** [comment]
I added this code to data/translation/ru_RU.php. In was empty. I think, if you click content->translation->save and public button, file ru_RU.php saved somewhere else. Not in data/translation. And admin translation not works. I placed this code and .CSV file with translations instead of creatin an array in it. And .CSV file is simple to edit (like in Magento).

**Comment by PierreRambaud** [comment]
I just tried by using the same locale, click on `content -> translation -> save and plublish` and I have files in `data/translation/`.
CSV files are not recognize per default only php file with `key => value` are loaded in `data/translation`directory.

**Comment by e-v-medvedev** [comment]
I`am id..t. I forgot to set correct permissions :-). Sorry.

**Comment by PierreRambaud** [comment]
No problem ;)
