### ISSUE TITLE
Remove StreamWrapper

### ISSUE THREAD

**Issue by e-v-medvedev** [GotCms/GotCms#288]
It`s not good, that there is now possibility to use only external files for scripts and views (there is no way to switch of rewriting files with data from DB). For example in MODx i can switch between using DB data or external file as template. I think it would be better to load data from file only.

**Comment by PierreRambaud** [comment]
You can too swtich between both, views, scripts and layouts are stored into templates directory.
But I agree with you, Streamwrapper must be removed. I change this title of your issue.

**Comment by e-v-medvedev** [comment]
I can edit them? but if i forget, i can erase all that i did in IDE. To prevent this, i must every time to reload file in admin. How can i fix this?

**Comment by PierreRambaud** [comment]
You must disable Stream Wrapper in configuration.

**Comment by PierreRambaud** [comment]
Will be release in 1.6.0 ;)

**Comment by e-v-medvedev** [comment]
I`ll be wait :-).
