### ISSUE TITLE
Error with redirection in script

### ISSUE THREAD

**Issue by e-v-medvedev** [GotCms/GotCms#289]
Redirection in script files not works. I addad line $this->redirect()->toUrl('/account'); in login script. But no result. The same page loaded (/login).

**Comment by PierreRambaud** [comment]
Hi,

In my script:
```
$this->redirect()->toUrl('/contact');
return true;
```
In my View: 
```
$return = $this->script('contact');
if ($return === true) {
    return;
}
```

Regards

**Comment by e-v-medvedev** [comment]
It didn`t help me. In my case i need redirect user after logout to login page.
In script logout.phtml i added this:
"$this->redirect()->toUrl('/login');
return true;"
And in view logout.phtml i added this:
"            <?php
				$return = $this->script('logout');
				if ($return === true) {
    				return;
				}
            ?>
"

This construction in script file works fine:
$this->getResponse()->getHeaders()->addHeaders(array('Location' => '/login'));
$this->getResponse()->sendHeaders(); 

Did i miss anything?

**Comment by PierreRambaud** [comment]
I don't know, Can you show me your view template and script template?  (Using Markdown if possible https://guides.github.com/features/mastering-markdown/)

**Comment by e-v-medvedev** [comment]
Content of script file
```
<?php
$session = new Zend\Session\Container('User');
$session->getManager()->destroy();
$this->getServiceLocator()->get('SmartceoAuthService')->clearIdentity();
$this->redirect()->toUrl('/login');
return true;
?>
```
And conten of view file
```
<div id="logout">
        <div id="leftcontainer">
            <h2>Выход</h2>
            <?php echo $this->partial('flash-messages'); ?>
            <?php
				$return = $this->script('logout');
				if ($return === true) {
    				return;
				}
            ?>

        </div>
</div>
```

**Comment by PierreRambaud** [comment]
Sorry for the delay, and sorry again but I can't reproduce this error :/

**Comment by e-v-medvedev** [comment]
Let`s forget about it :-). Code with sendHeaders works fine.

**Comment by PierreRambaud** [comment]
Thanks a lot ;)
