### ISSUE TITLE
Blog error

### ISSUE THREAD

**Issue by e-v-medvedev** [GotCms/GotCms#290]
! can`t create "Third category" in blog. Field "Document type" is empty and new categoy don`t save. Error message: "Invalid document data".

**Comment by PierreRambaud** [comment]
I need more information to understand what's exactly happened :/

**Comment by e-v-medvedev** [comment]
But there is no more information. Error_log emmpty. No JS errors. I rightclicked on Main page for blog, selected in context menu "New" item and try to fill 3 fields: Name, Url Key and Document Type. But there was no options in Document Type select box. That`s all.

**Comment by e-v-medvedev** [comment]
I also can`t create second level subcategories. Only articles. Only "Blog Ticket" document type available.

**Comment by PierreRambaud** [comment]
You must edit the Document type in Development section and allow other document type as children.
Some document can't have children if it's not specified in the parent document type.

**Comment by e-v-medvedev** [comment]
Do you have some manual for this case?

**Comment by e-v-medvedev** [comment]
I found it :-). All works fine.
