### ISSUE TITLE
Document import manual

### ISSUE THREAD

**Issue by e-v-medvedev** [GotCms/GotCms#291]
Is there any manual about import documents into GotCMS or db structure diagramm?

**Comment by PierreRambaud** [comment]
No manual for it, by using export you will see a xml document and view how it works, nothing more :/

**Comment by e-v-medvedev** [comment]
What export?

**Comment by PierreRambaud** [comment]
In backup module, you can export / import documents. Otherwise there is no solution to import document without using directly your database.
