### ISSUE TITLE
Nested Navigation?

### ISSUE THREAD

**Issue by dlanz** [GotCms/GotCms#295]
Is nested navigation supported?  I seem to be able to drag and drop the order of pages, but I can't seem to specify a hierarchy.  If this is not supported, it would be great for it to be added.

**Comment by PierreRambaud** [comment]
Hi,

I don't have any time to add features :/
To order page, you can order them directly in the backend by moving them in the treeview, the navigation will be ordering pages.

Regards

**Comment by dlanz** [comment]
Okay, no worries.  If I was more versed in ZF2 I'd try to contribute with the feature, maybe in the future though. Thank you.
