### ISSUE TITLE
An exception was raised while creating "CustomModules"; no instance returned

### ISSUE THREAD

**Issue by burdem** [GotCms/GotCms#297]
Hi there,
At last step of installation, something went wrong. 

```
OK - Create database
OK - Insert data
OK - Insert translations
OK - Create users and roles
ERROR - Install template
Create configuration file
```

Error: 
```
An exception was raised while creating "CustomModules"; no instance returned
```

I didn't change anything in custom module pages. What is the problem, any idea?

**Comment by PierreRambaud** [comment]
Hi and sorry, I was in vacation.
Did you change something in the code?

Regards
