### ISSUE TITLE
Issue while creating the adimin users

### ISSUE THREAD

**Issue by divyasreem** [GotCms/GotCms#298]
I am not able to create the admin user, can you help me out to complete this process.

**Comment by PierreRambaud** [comment]
Can you tell me more about what's happened, maybe some logs?

**Comment by divyasreem** [comment]
After the installation process, final step I will get to create an admin
user , those details are not getting stored in database. After filling the
details for admin user it just redirecting to the login page for admin but
details are not getting stored in DB.

Please guide me how to proceed. Its an important for me to complete that
process today.

On Mon, May 23, 2016 at 12:58 PM, GoT <notifications@github.com> wrote:

> Can you tell me more about what's happened, maybe some logs?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GotCms/GotCms-legacy/issues/298#issuecomment-220906187>
>



-- 
Divya Sree

Software Engineer
Mantra Labs Pvt Ltd, Bangalore

M:+91 9986101098 | W: www.mantralabsglobal.com
<http://mantralabsglobal.com/>

**Comment by PierreRambaud** [comment]
Can you show php errors logs?

**Comment by divyasreem** [comment]
Is it possible to have a skype call so that it will be easy for me to
complete the process quickly.


Thanks,
Divya

On Mon, May 23, 2016 at 1:11 PM, GoT <notifications@github.com> wrote:

> Can you show php errors logs?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GotCms/GotCms-legacy/issues/298#issuecomment-220908396>
>



-- 
Divya Sree

Software Engineer
Mantra Labs Pvt Ltd, Bangalore

M:+91 9986101098 | W: www.mantralabsglobal.com
<http://mantralabsglobal.com/>

**Comment by PierreRambaud** [comment]
Nop sorry, currently at work and not able to do it :/

**Comment by divyasreem** [comment]
Thanks for your support.

But I tried not getting any error in log file.

Please help me.

On Mon, May 23, 2016 at 1:19 PM, GoT <notifications@github.com> wrote:

> Nop sorry, currently at work and not able to do it :/
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GotCms/GotCms-legacy/issues/298#issuecomment-220909977>
>



-- 
Divya Sree

Software Engineer
Mantra Labs Pvt Ltd, Bangalore

M:+91 9986101098 | W: www.mantralabsglobal.com
<http://mantralabsglobal.com/>

**Comment by PierreRambaud** [comment]
Did the final step was complete in the final step and did the reload load the admin login page?

**Comment by divyasreem** [comment]
After the final step it is redirecting to localhost page with all the
folders in my XAMPP, If I tried to go to the project folder it goes to
login page. (http://localhost/GotCms-legacy/public/admin) after entering
the credentials  getting this screen.

PFA

On Mon, May 23, 2016 at 1:31 PM, GoT <notifications@github.com> wrote:

> Did the final step was complete in the final step and did the reload load
> the admin login page?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GotCms/GotCms-legacy/issues/298#issuecomment-220912105>
>



-- 
Divya Sree

Software Engineer
Mantra Labs Pvt Ltd, Bangalore

M:+91 9986101098 | W: www.mantralabsglobal.com
<http://mantralabsglobal.com/>

**Comment by PierreRambaud** [comment]
Url look wrong `http://localhost/GotCms-legacy/public/admin` this project work with virtualhost, don't know how it work with XAMPP or WAMPP :/

**Comment by divyasreem** [comment]
ok give me some time I will configure the virtualhost

On Mon, May 23, 2016 at 1:38 PM, GoT <notifications@github.com> wrote:

> Url look wrong http://localhost/GotCms-legacy/public/admin this project
> work with virtualhost, don't know how it work with XAMPP or WAMPP :/
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GotCms/GotCms-legacy/issues/298#issuecomment-220913592>
>



-- 
Divya Sree

Software Engineer
Mantra Labs Pvt Ltd, Bangalore

M:+91 9986101098 | W: www.mantralabsglobal.com
<http://mantralabsglobal.com/>

**Comment by divyasreem** [comment]
I configured the virtual host, But now I am not getting the installation
process it is going to login screen directly.(
https://got-cms.com/admin/config/user/login/L2FkbWlu)



On Mon, May 23, 2016 at 1:40 PM, Divya Sree <divya@mantralabsglobal.com>
wrote:

> ok give me some time I will configure the virtualhost
>
> On Mon, May 23, 2016 at 1:38 PM, GoT <notifications@github.com> wrote:
>
>> Url look wrong http://localhost/GotCms-legacy/public/admin this project
>> work with virtualhost, don't know how it work with XAMPP or WAMPP :/
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/GotCms/GotCms-legacy/issues/298#issuecomment-220913592>
>>
>
>
>
> --
> Divya Sree
>
> Software Engineer
> Mantra Labs Pvt Ltd, Bangalore
>
> M:+91 9986101098 | W: www.mantralabsglobal.com
> <http://mantralabsglobal.com/>
>



-- 
Divya Sree

Software Engineer
Mantra Labs Pvt Ltd, Bangalore

M:+91 9986101098 | W: www.mantralabsglobal.com
<http://mantralabsglobal.com/>

**Comment by PierreRambaud** [comment]
You must remove `config/autoload/local.php` and rerun installation.

**Comment by divyasreem** [comment]
getting the same issue it is not getting stored in DB

On Mon, May 23, 2016 at 2:04 PM, GoT <notifications@github.com> wrote:

> You must remove config/autoload/local.php and rerun installation.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GotCms/GotCms-legacy/issues/298#issuecomment-220918929>
>



-- 
Divya Sree

Software Engineer
Mantra Labs Pvt Ltd, Bangalore

M:+91 9986101098 | W: www.mantralabsglobal.com
<http://mantralabsglobal.com/>

**Comment by PierreRambaud** [comment]
It's really hard to help without logs or infos :/

**Comment by divyasreem** [comment]
Is it possible to provide me the dump for the user login, so that I can try
to login and check.

or is there any CMS plugin is available to proceed in ZF2

On Mon, May 23, 2016 at 2:11 PM, GoT <notifications@github.com> wrote:

> It's really hard to help without logs or infos :/
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GotCms/GotCms-legacy/issues/298#issuecomment-220920466>
>



-- 
Divya Sree

Software Engineer
Mantra Labs Pvt Ltd, Bangalore

M:+91 9986101098 | W: www.mantralabsglobal.com
<http://mantralabsglobal.com/>

**Comment by PierreRambaud** [comment]
I don't really understand what do you mean by dump user login and cms plugins :/
Make sure you use the good database by checking values in `config/autoload/local.php`. 
Don't forget to activate error_log, error_reporting,  and display_errors, restart apache / nginx and rerun its.

**Comment by divyasreem** [comment]
I need to created a CMS application using zend framework, so looking for
the modules which supports this feature.

On Mon, May 23, 2016 at 2:46 PM, GoT <notifications@github.com> wrote:

> I don't really understand what do you mean by dump user login and cms
> plugins :/
> Make sure you use the good database by checking values in
> config/autoload/local.php.
> Don't forget to activate error_log, error_reporting, and display_errors,
> restart apache / nginx and rerun its.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GotCms/GotCms-legacy/issues/298#issuecomment-220928225>
>



-- 
Divya Sree

Software Engineer
Mantra Labs Pvt Ltd, Bangalore

M:+91 9986101098 | W: www.mantralabsglobal.com
<http://mantralabsglobal.com/>

**Comment by PierreRambaud** [comment]
Try to debug php here https://github.com/GotCms/GotCms-legacy/blob/master/module/GcFrontend/src/GcFrontend/Controller/InstallController.php#L693
